filebeat:
  inputs:
    - type: log
      paths:
        - /var/lib/docker/containers/*/*.log
      multiline:
        pattern: '^\['                  # Detects lines starting with '[' for multiline logs
        negate: true
        match: after
      fields:
        log_source: docker
      fields_under_root: true
      processors:
        - add_docker_metadata: {}

output.elasticsearch:
  # CHANGE THIS: replace 192.168.4.103 with the IP of your Elasticsearch host
  hosts: ["http://192.168.4.103:9200"]
  index: "filebeat-new"

setup.template.name: "filebeat-new"
setup.template.pattern: "filebeat-new*"
setup.template.enabled: true
setup.ilm.enabled: true
setup.ilm.overwrite: true
setup.ilm.policy_name: "filebeat-new-policy"
setup.ilm.rollover_alias: "filebeat-new"
setup.ilm.pattern: '{now/d}-000001'
setup.ilm.policy_file: "/usr/share/filebeat/filebeat-ilm.json"

setup.template.mappings:
  properties:
    log:
      properties:
        message:
          type: text
    timestamp:
      type: date

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
