version: "3.0"

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/mark/config/sabnzbd:/config
      - /media/download/complete:/downloads
      - /media/download/incomplete:/incomplete-downloads #optional
      - /media/download/watch:/media/watch
      - /media/toshibaDrive/TV:/media/TV
      - /media/toshibaDrive/MOVIES/:/media/MOVIES
    ports:
      - 8088:8080
      - 9099:9090
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.1
  transmission:
    image: linuxserver/transmission:3.00-r5-ls137
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/mark/config/transmission:/config
      - /media/download/complete:/downloads
      - /media/download/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.3
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: host
    volumes:
      - /home/mark/config/plex:/config
      - /media/toshibaDrive/TV:/data/tvshows
      - /media/toshibaDrive/MOVIES:/data/movies
      - /media/transcode:/transcode
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=002 #optional
    volumes:
      - /home/mark/config/radarr:/config
      - /media/toshibaDrive/MOVIES:/movies
      - /media/download/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.5
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=002 #optional
    volumes:
      - /home/mark/config/sonarr:/config
      - /media/toshibaDrive/TV:/tv
      - /media/download/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.6
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/mark/config/mylar3:/config
      - /media/toshibaDrive/COMICS:/comics
      - /media/download/complete:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.7
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /home/mark/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.4

  readarr:
    image: cr.hotio.dev/hotio/readarr
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /home/mark/config/readarr:/config
      - /media/toshibaDrive/eBooks:/EBOOKS
      - /media/download/complete:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      htpc_net:
        ipv4_address: 172.66.1.8
networks:
  htpc_net:
    ipam:
      driver: default
      config:
        - subnet: 172.66.0.0/16
