version: '3'
services:
  elasticsearch:
    image: 'ind3x/rpi-elasticsearch'
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS="-Des.index.number_of_replicas=0"
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - network.bind_host=0.0.0.0
<<<<<<< HEAD
      - network.publish_host=${BEATS_HOST}
=======
      - network.publish_host=192.168.1.4
>>>>>>> 0c21d3a (working pi elastic and kibana)
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
      - '9300:9300'
    restart: unless-stopped
    networks:
      - esnet
<<<<<<< HEAD

=======
>>>>>>> 0c21d3a (working pi elastic and kibana)
  kibana:
    image: 'ind3x/rpi-kibana'
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    ports:
      - '5601:5601'
    restart: unless-stopped
    networks:
      - esnet
    depends_on:
      - elasticsearch
<<<<<<< HEAD

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H tcp://${BEATS_HOST}:2375  # Connect to the remote Docker instance
    ports:
      - '9191:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'  # Required to access Docker API
    restart: unless-stopped
    networks:
      - esnet
    depends_on:
      - elasticsearch

networks:
  esnet:
    driver: bridge

volumes:
  esdata:
    driver: local

=======
networks:
  esnet:
    driver: bridge
volumes:
  esdata:
    driver: local
>>>>>>> 0c21d3a (working pi elastic and kibana)
