# services.yml - Set to true to enable a service, false to disable it.
# This file is read on every docker compose up.
# Services marked false will never be pulled or started.

emby: false
filebeat: true
flaresolverr: true
jellyfin: true
metricbeat: true
mylar3: true
plex: true
prowlarr: true
radarr: true
readarr: true
sabnzbd: true
seerr: true
sonarr: true
tautulli: true
transmission: true
