---
apiVersion: v1
kind: Service
metadata:
  name: livrarr
  namespace: htpc
  labels:
    app.kubernetes.io/name: livrarr
    app.kubernetes.io/part-of: arrs-stack
spec:
  selector:
    app.kubernetes.io/name: livrarr
  type: ClusterIP
  ports:
    - name: http
      port: 8686
      targetPort: 8686
      protocol: TCP
