---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: htpc
  labels:
    app.kubernetes.io/name: audiobookshelf
    app.kubernetes.io/part-of: arrs-stack
    app.kubernetes.io/component: media-server
spec:
  selector:
    app.kubernetes.io/name: audiobookshelf
  type: ClusterIP
  ports:
    - name: http
      port: 13378
      targetPort: 80
      protocol: TCP
