---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: htpc
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: arrs-stack
    app.kubernetes.io/component: media-server
spec:
  selector:
    app.kubernetes.io/name: jellyfin
  type: ClusterIP
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
    - name: https
      port: 8920
      targetPort: 8920
      protocol: TCP
    - name: local-disc
      port: 7359
      targetPort: 7359
      protocol: UDP
    - name: dlna
      port: 1900
      targetPort: 1900
      protocol: UDP
