metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

setup.ilm.enabled: true
setup.ilm.policy_name: "metricbeat"
setup.ilm.overwrite: true

setup.template.enabled: true
setup.template.overwrite: true
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

setup.kibana:
  host: "http://192.168.4.103:5601"

output.elasticsearch:
  hosts: ["192.168.4.103:9200"]

