metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

setup.kibana:
  # CHANGE THIS: replace 192.168.4.103 with the IP of your Kibana host
  host: "http://192.168.4.103:5601"


output.elasticsearch:
  # CHANGE THIS: replace 192.168.4.103 with the IP of your Elasticsearch host
  hosts: ["192.168.4.103:9200"]
