---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: htpc
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/part-of: arrs-stack
    app.kubernetes.io/component: downloader
spec:
  selector:
    app.kubernetes.io/name: sabnzbd
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 9090
      targetPort: 9090
      protocol: TCP
