---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: observability
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: arrs-stack
    app.kubernetes.io/component: search
spec:
  selector:
    app.kubernetes.io/name: elasticsearch
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
