---
apiVersion: v1
kind: Service
metadata:
  name: shelfmark
  namespace: htpc
  labels:
    app.kubernetes.io/name: shelfmark
    app.kubernetes.io/part-of: arrs-stack
spec:
  selector:
    app.kubernetes.io/name: shelfmark
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
