---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: observability
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/part-of: arrs-stack
    app.kubernetes.io/component: dashboard
spec:
  selector:
    app.kubernetes.io/name: kibana
  type: ClusterIP
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
